// Fused causal depthwise-convolution/state update for Qwen3.6 linear
// attention. INPUT0 and OUTPUT0 are token-major [1,1,T,8192]; INPUT1,
// INPUT2, and OUTPUT1 are feature-major [1,1,8192,4]. The stock graph
// concatenates four carried samples, computes a width-four cross-correlation,
// drops its first output, applies SiLU, and keeps the last four concatenated
// samples. One parameterized kernel performs that exact boundary without the
// FC-output transpose or blocked-convolution reorders.

#define IQ36_LINEAR_FEATURES 8192
#define IQ36_CONV_WIDTH 4

__kernel void iq36_linear_conv_swish(
    const __global INPUT0_TYPE* qkv,
    const __global INPUT1_TYPE* previous_state,
    const __global INPUT2_TYPE* weights,
    __global OUTPUT0_TYPE* activated_qkv,
    __global OUTPUT1_TYPE* next_state) {
  const int feature = (int)get_global_id(0);
  const int token = (int)get_global_id(1);
  const int token_count = (int)get_global_size(1);
  if (feature >= IQ36_LINEAR_FEATURES || token >= token_count) {
    return;
  }

  OUTPUT0_TYPE sum = (OUTPUT0_TYPE)0;
  const int state_base = feature * IQ36_CONV_WIDTH;
  for (int tap = 0; tap < IQ36_CONV_WIDTH; ++tap) {
    // Stock GroupConvolution sees [state(4), qkv(T)], produces T+1 rows,
    // then Slice drops row zero. Output token t therefore begins at combined
    // index t+1.
    const int combined = token + 1 + tap;
    const INPUT0_TYPE value =
        combined < IQ36_CONV_WIDTH
            ? (INPUT0_TYPE)previous_state[state_base + combined]
            : qkv[(combined - IQ36_CONV_WIDTH) *
                      IQ36_LINEAR_FEATURES +
                  feature];
    sum = fma(
        (OUTPUT0_TYPE)value,
        (OUTPUT0_TYPE)weights[state_base + tap], sum);
  }
  // The stock convolution publishes F16 before activation_ref__f16.  Preserve
  // both rounding boundaries: first the convolution output, then Swish's
  // half-typed expression generated by the GPU activation JIT.
  const OUTPUT0_TYPE convolved = sum;
  const OUTPUT0_TYPE activated =
      convolved /
      ((OUTPUT0_TYPE)1 + exp(-(OUTPUT0_TYPE)convolved));
  activated_qkv[token * IQ36_LINEAR_FEATURES + feature] = activated;

  if (token == 0) {
    // The next request retains the final four rows of [state(4), qkv(T)].
    for (int slot = 0; slot < IQ36_CONV_WIDTH; ++slot) {
      const int combined = token_count + slot;
      const INPUT0_TYPE value =
          combined < IQ36_CONV_WIDTH
              ? (INPUT0_TYPE)previous_state[state_base + combined]
              : qkv[(combined - IQ36_CONV_WIDTH) *
                        IQ36_LINEAR_FEATURES +
                    feature];
      next_state[state_base + slot] = (OUTPUT1_TYPE)value;
    }
  }
}
